### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by kkmann** [kkmann/otsd.jl#1]
Stuff that is still missing an needs to be done:
 - [ ] clean up code (do not need BSDesigns anymore)
 - [ ] improve the formulation of a custom optimization problem
 - [ ] verify that conditional constraints will work as anticipated
 - [ ] verify that non-point prior scores work fine as well
 - [ ] come up with a few good heuristics on how to select smoothing parameters, initial value, etc.
 - [ ] decide whether we are supporting everything we want (currently: everything that is based on sample size and conditional power, i.e., expected sample size, power, expected/conditional power)
 - [ ] They current implementation of the smoothness penalty is entire numerically motivated, add some stuff in this direction  
 - [ ] write test suit
 - [ ] document, document, document!
